# Rust formatting configuration
# https://rust-lang.github.io/rustfmt/

edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Auto"
use_small_heuristics = "Default"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
# Note: The following options require nightly Rust
# format_strings = true
# normalize_comments = true
# wrap_comments = true
# comment_width = 80
